### PR TITLE
Customize the script so it supports another user account on the same machine

### PR DESCRIPTION
**Pull request by bokay**
Allow us to run: `sh mac ANOTHER_USER=1 2>&1 | tee ~/laptop.log`

Note the `ANOTHER_USER=1` flag which would invoke the following:

1. Skip install homebrew and packages
2. Adding `ZSH_DISABLE_COMPFIX=true` to the top of .zshrc
3. Run `sudo chsh -s $(whereis zsh) "$USER"`

This is based on @bokay notes: https://github.com/civilcode/playbook/pull/90#issuecomment-451971051

TODOES
- [x] Test pairing install in a VM 
- [x] Test nominal install in a VM

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
A little confused here @bokay:

The readme instructions are as follows:

*Install (main user account)*

```
curl --remote-name https://raw.githubusercontent.com/civilcode/laptop/master/mac
less mac
sh mac 2>&1 ANOTHER_USER=1 | tee ~/laptop.log
```

and...

*Install (pairing account)*

```
curl --remote-name https://raw.githubusercontent.com/civilcode/laptop/master/mac
less mac
sh mac 2>&1 | tee ~/laptop.log
```

But the script is:

```
if [ $1 == "ANOTHER_USER=1" ]; then
  setup_pairing_account
else
  install_homebrew
fi
```

Seems like the README instructions are reversed?

I tried them in the order that I would have expected:

```
# main account
curl --remote-name https://raw.githubusercontent.com/civilcode/laptop/master/mac
less mac
sh mac 2>&1 | tee ~/laptop.log

# then pairing account
curl --remote-name https://raw.githubusercontent.com/civilcode/laptop/master/mac
less mac
sh mac 2>&1 ANOTHER_USER=1 | tee ~/laptop.log
```

But I got the following error when I ran these:

screen shot 2019-02-08 at 7 03 39 pm

Thoughts?

**Comment by bokay** [comment]
@nicholasjhenry Indeed, the instructions were reversed.
As of the issue, that's because the links are pointing to master, and not the branch. The links will be okay once this PR is merged.

`https://raw.githubusercontent.com/civilcode/laptop/master/mac`

**Comment by nicholasjhenry** [comment]
Thank you, @bokay! I probably should finish for the day ;-)

**Comment by nicholasjhenry** [comment]
@bokay Unfortunately the install for the pairing account fails using the following command:

```
curl --remote-name https://raw.githubusercontent.com/civilcode/laptop/chore/support-pairing-account/mac
less mac
sh mac 2>&1 ANOTHER_USER=1 | tee ~/laptop.log
```

screen shot 2019-02-09 at 9 36 12 am


Something to look at next Friday.

**Comment by bokay** [comment]
@nicholasjhenry The doc has another mistake. It should be the opposite:
`sh mac ANOTHER_USER=1 2>&1 `

**Pull request merged**
